"""Conversation state constants shared across handlers."""

(
    EXPENSE_AMOUNT,
    EXPENSE_CATEGORY,
    EXPENSE_DESCRIPTION_DECISION,
    EXPENSE_DESCRIPTION_INPUT,
    INCOME_AMOUNT,
    INCOME_CATEGORY,
    CATEGORY_MENU,
    CATEGORY_ADD_NAME,
    CATEGORY_ADD_TYPE,
    CATEGORY_RENAME_SELECT,
    CATEGORY_RENAME_NAME,
    BUDGET_CATEGORY_SELECT,
    BUDGET_AMOUNT_INPUT,
    GOAL_NAME_INPUT,
    GOAL_TARGET_INPUT,
    GOAL_CONTRIBUTION_SELECT,
    GOAL_CONTRIBUTION_AMOUNT,
    ONBOARDING_WELCOME,
    ONBOARDING_DEMO,
    ONBOARDING_CATEGORY_CHOICES,
    ONBOARDING_CUSTOM_INPUT,
    ONBOARDING_COMPLETE,
) = range(22)


